#define EVENT_NULL 0
#define EVENT_TURN_LEFT_MULTI 1
#define EVENT_TURN_RIGHT_MULTI 2
#define EVENT_TURN_LEFT_SINGLE 4
#define EVENT_TURN_RIGHT_SINGLE 8
#define EVENT_BUTTON_SHORT 16
#define EVENT_BUTTON_LONG 32
